[package]
org = "ballerina"
name = "jwt"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "cache"
version = "@stdlib.cache.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "encoding"
version = "@stdlib.encoding.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "@stdlib.uuid.version@"

[[platform.java11.dependency]]
path = "../jwt-native/build/libs/jwt-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "jwt"
version = "@project.version@"
