[package]
org = "ballerina"
name = "jwt"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../jwt-native/build/libs/jwt-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "jwt"
version = "@project.version@"
