[package]
org = "ballerina"
name = "jwt"
version = "2.2.1"
authors = ["Ballerina"]
keywords = ["security", "authentication", "jwt", "jwk", "jws"]
repository = "https://github.com/ballerina-platform/module-ballerina-jwt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/jwt-native-2.2.1-SNAPSHOT.jar"
