[package]
org = "ballerina"
name = "jwt"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["security", "authentication", "jwt", "jwk", "jws"]
repository = "https://github.com/ballerina-platform/module-ballerina-jwt"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/jwt-native-2.1.0-SNAPSHOT.jar"
